/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as ApiVerifyRouteImport } from './routes/api/verify'
import { Route as ExamplesMultipleWidgetsRouteImport } from './routes/examples/multiple-widgets'
import { Route as ExamplesScriptLoadingRouteImport } from './routes/examples/script-loading'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyRoute = ApiVerifyRouteImport.update({
  id: '/api/verify',
  path: '/api/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesMultipleWidgetsRoute = ExamplesMultipleWidgetsRouteImport.update({
  id: '/examples/multiple-widgets',
  path: '/examples/multiple-widgets',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesScriptLoadingRoute = ExamplesScriptLoadingRouteImport.update({
  id: '/examples/script-loading',
  path: '/examples/script-loading',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/api/verify': typeof ApiVerifyRoute
  '/examples/multiple-widgets': typeof ExamplesMultipleWidgetsRoute
  '/examples/script-loading': typeof ExamplesScriptLoadingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/api/verify': typeof ApiVerifyRoute
  '/examples/multiple-widgets': typeof ExamplesMultipleWidgetsRoute
  '/examples/script-loading': typeof ExamplesScriptLoadingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/api/verify': typeof ApiVerifyRoute
  '/examples/multiple-widgets': typeof ExamplesMultipleWidgetsRoute
  '/examples/script-loading': typeof ExamplesScriptLoadingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/playground'
    | '/api/verify'
    | '/examples/multiple-widgets'
    | '/examples/script-loading'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/playground'
    | '/api/verify'
    | '/examples/multiple-widgets'
    | '/examples/script-loading'
  id:
    | '__root__'
    | '/'
    | '/playground'
    | '/api/verify'
    | '/examples/multiple-widgets'
    | '/examples/script-loading'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlaygroundRoute: typeof PlaygroundRoute
  ApiVerifyRoute: typeof ApiVerifyRoute
  ExamplesMultipleWidgetsRoute: typeof ExamplesMultipleWidgetsRoute
  ExamplesScriptLoadingRoute: typeof ExamplesScriptLoadingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify': {
      id: '/api/verify'
      path: '/api/verify'
      fullPath: '/api/verify'
      preLoaderRoute: typeof ApiVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/multiple-widgets': {
      id: '/examples/multiple-widgets'
      path: '/examples/multiple-widgets'
      fullPath: '/examples/multiple-widgets'
      preLoaderRoute: typeof ExamplesMultipleWidgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/script-loading': {
      id: '/examples/script-loading'
      path: '/examples/script-loading'
      fullPath: '/examples/script-loading'
      preLoaderRoute: typeof ExamplesScriptLoadingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlaygroundRoute: PlaygroundRoute,
  ApiVerifyRoute: ApiVerifyRoute,
  ExamplesMultipleWidgetsRoute: ExamplesMultipleWidgetsRoute,
  ExamplesScriptLoadingRoute: ExamplesScriptLoadingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
